### PR TITLE
Remove threedd from group list

### PR DESCRIPTION
**Pull request by unkcpz**
Hi @CasperWA, I think this will fix the duplicate 'three-dimensional' in the group list mentioned previously by Nicola. I have pushed the change and tested it in https://optimadeclient.matcloud.xyz/.

### CODE REVIEW

**Comment by unkcpz** [comment]
As I asked in the email thread, what is your preference on keeping this repository in your github account or maybe move it to materials-cloud organization?  Also pinning @giovannipizzi for comment.

**Comment by unkcpz** [comment]
🧐Hmm.. Although https://optimadeclient.matcloud.xyz/ works fine but I find the iframe of the tool in materials cloud broken https://dev-www.materialscloud.org/work/tools/optimadeclient. The error message in browser is:

```
Refused to frame 'https://optimadeclient.matcloud.xyz/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

Any idea of this? I am not sure this can be fix on this voila or on materials cloud side.

**Comment by CasperWA** [comment]
> As I asked in the email thread, what is your preference on keeping this repository in your github account or maybe move it to materials-cloud organization? Also pinning @giovannipizzi for comment.

For this particular repository, I don't see a reason to move it. The specific version that's on Materials Cloud is already under the Materials Cloud organization: [materialscloud-org/tools-optimade-client](https://github.com/materialscloud-org/tools-optimade-client).

**Comment by CasperWA** [comment]
I think this PR should be moved to that repository as well (materialscloud-org/tools-optimade-client).

**Comment by unkcpz** [comment]
Sorry @CasperWA, I am a bit confused with the repo [tools-optimade-client](https://github.com/materialscloud-org/tools-optimade-client). Now the optimateclient  in dev server and server are all using dokku. You mean I can `git push dokku` from  repo `tools-optimade-client`?

**Comment by CasperWA** [comment]
> Sorry @CasperWA, I am a bit confused with the repo [tools-optimade-client](https://github.com/materialscloud-org/tools-optimade-client). Now the optimateclient in dev server and server are all using dokku. You mean I can `git push dokku` from repo `tools-optimade-client`?

Yes. The `tools-optimade-client` is the Materials Cloud-specific version of the client with some extra customization, use of the Materials Cloud theme, a button to use the structures in the QE input generator, etc.

**Comment by unkcpz** [comment]
@CasperWA thanks a lot! I close this and open one in repo there https://github.com/materialscloud-org/tools-optimade-client/pull/100.

**Pull request closed without merging**
