### PR TITLE
Integrate AiiDAlab app into repository.

### PR DESCRIPTION
**Pull request by csadorf**
- Add AiiDAlab metadata and requirements.
- Add app notebook and start module.

### CODE REVIEW

**Comment by csadorf** [comment]
You can test the dependency specification with [repo2env](https://pypi.org/project/repo2env/):
```bash
$ pip install repo2env
$ repo2env git+https://github.com/CasperWA/voila-optimade-client.git@integrate-aiidalab-app | jq
{
  "python_requirements": [
    "appdirs~=1.4.4",
    "cachecontrol[filecache]~=0.12.6",
    "ipywidgets~=7.6",
    "ipywidgets-extended~=1.1",
    "nglview~=3.0",
    "optimade~=0.16.1",
    "pandas~=1.3",
    "requests~=2.26",
    "widget_periodictable~=2.1"
  ]
}
```

**Comment by csadorf** [comment]
@CasperWA Did you get a chance to look at this?

**Comment by CasperWA** [comment]
> @CasperWA Did you get a chance to look at this?

Not yet - I'll take a look ASAP. Working my way through everything :)
How do we test this in AiiDAlab? Does this needs to be part of the default branch before it can be tested or can you test your PR branch already? Maybe not.

**Comment by csadorf** [comment]
> > @CasperWA Did you get a chance to look at this?
> 
> Not yet - I'll take a look ASAP. Working my way through everything :)
> How do we test this in AiiDAlab? Does this needs to be part of the default branch before it can be tested or can you test your PR branch already? Maybe not.

I could add this branch to the registry and then you can try to install directly from there. For proper testing, you would ideally create a pre-release tag on this branch.

**Comment by csadorf** [comment]
@CasperWA Please let me know if you would like me to add this branch to the app registry. Creating a pre-release version would then involve creating a tag like "2021.08.1rc1" on one of the branch's commits. That version can then be installed on [https://demo-staging.aiidalab.net](https://demo-staging.aiidalab.net) .

**Comment by CasperWA** [comment]
For ref.: @csadorf will set up AiiDAlab demo to point to this branch for testing, and will also push a tag pointing to the commit in this PR. Then this branch can be used for testing the use of this repo with AiiDAlab and any integration issues can be resolved here before merging into `develop`.

**Comment by csadorf** [comment]
@CasperWA FYI, Looks like there is a little bug in the registry code which prevents the tag to be picked up from the branch at the moment. I will fix that as soon as possible.

**Comment by csadorf** [comment]
@CasperWA The bug in the registry is resolved and the app version is now listed on the app index:
```console
$ curl https://aiidalab.github.io/aiidalab-registry/api/v1/apps/aiidalab-optimade.json | jq .releases | head -n 20
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3643  100  3643    0     0  78540      0 --:--:-- --:--:-- --:--:-- 79195
{
  "2021.8.4rc0+aiidalab": {
    "environment": {
      "python_requirements": [
        "appdirs~=1.4.4",
        "cachecontrol[filecache]~=0.12.6",
        "ipywidgets~=7.6",
        "ipywidgets-extended~=1.1",
        "nglview~=3.0",
        "optimade~=0.16.1",
        "pandas~=1.3",
        "requests~=2.26",
        "widget_periodictable~=2.1"
      ]
    },
    "url": "git+https://github.com/CasperWA/voila-optimade-client.git@1b215cabac504aae727e35809aa7473d9ea0aaee"
  },
  "v1.0.0": {
    "environment": {
      "python_requirements": [
```
I can also install that version on the staging server. However, you must do it through the terminal, because the app requires `requests~=2.26` and we only have version 2.25.1 installed.
The command to install the app is: `$  aiidalab install aiidalab-optimade --pre  --python=''`
Screen Shot 2021-08-05 at 17 28 20

The app opens properly, however I did not directly test it:
Screen Shot 2021-08-05 at 17 28 56

I recommend that we proceed to delete this tag, merge this branch and I update the apps registry entry to point to `develop`. Any future tagged versions would then automatically be released on the app store. Once the requests version on the staging server is updated, you can then also directly install those releases through the app manager.

Or we wait until either the requests version has been updated and/or the automated app dependency installation flow has been fully implemented and released. In that case you could test the full installation flow and the app itself before merge.

What would you prefer?

**Comment by CasperWA** [comment]
I'll relax the requirements I think, since there is no reason to disallow `requests` v2.25 in this case. Most likely for other cases as well.

In terms of merging this branch and removing the tag. If I want to test and update stuff, can I install a branch in AiiDAlab demo instead of a tag?

**Comment by csadorf** [comment]
> I'll relax the requirements I think, since there is no reason to disallow `requests` v2.25 in this case. Most likely for other cases as well.

Ok, sure, that's another possibility.

> In terms of merging this branch and removing the tag. If I want to test and update stuff, can I install a branch in AiiDAlab demo instead of a tag?

To just test the app function, you can always check out your repository to whatever commit you like in the terminal.

To test the AiiDAlab installation flow, you have to create releases, which are currently configured to be tagged commits on this branch. If you want to avoid tags, we could change the [registry entry](https://github.com/aiidalab/aiidalab-registry/blob/8b6fbde586c2652608607151f787a86349d461cb/apps.yaml#L19) to `git+https://github.com/CasperWA/voila-optimade-client.git@integrate-aiidalab-app` in which case the `integrate-aiidalab-app` version in the app store would always refer to the tip of this branch (with minor delay of about 15-30mins). I would recommend to use tags instead, but it is up to you of course.

The [documentation on the release specification](https://github.com/aiidalab/aiidalab-registry#release-specification) outlines how to create releases based on a git branch.

**Comment by CasperWA** [comment]
> > In terms of merging this branch and removing the tag. If I want to test and update stuff, can I install a branch in AiiDAlab demo instead of a tag?
> 
> To just test the app function, you can always check out your repository to whatever commit you like in the terminal.

Sure, okay.

> To test the AiiDAlab installation flow, you have to create releases, which are currently configured to be tagged commits on this branch. If you want to avoid tags, we could change the [registry entry](https://github.com/aiidalab/aiidalab-registry/blob/8b6fbde586c2652608607151f787a86349d461cb/apps.yaml#L19) to `git+https://github.com/CasperWA/voila-optimade-client.git@integrate-aiidalab-app` in which case the `integrate-aiidalab-app` version in the app store would always refer to the tip of this branch (with minor delay of about 15-30mins). I would recommend to use tags instead, but it is up to you of course.

Let's do tags then. Let me just make a few changes in this branch before merging (relax requirements and try to merge the notebooks).
I'll then remove the tag here, merge it and make a new release.

The registry entry should be updated to point to this repository in general then.

> The [documentation on the release specification](https://github.com/aiidalab/aiidalab-registry#release-specification) outlines how to create releases based on a git branch.

Cheers. I've resorted recently to simply go through you for all of this directly instead, since I wasn't sure how far the development has gone for the different releases of AiiDAlab. But I'll refer to this document going forward then.

**Comment by csadorf** [comment]
> Cheers. I've resorted recently to simply go through you for all of this directly instead, since I wasn't sure how far the development has gone for the different releases of AiiDAlab. But I'll refer to this document going forward then.

Please feel free to keep asking me if anything is unclear. I'll make sure to point you to the right resources.

**Comment by csadorf** [comment]
Just a quick note: Version `2021.8.6` is not yet available on the demo-staging, because it comes with `optimade 0.14.1`, whereas this app requires `~=0.16.1`. This is not a big deal, I'll update AiiDAlab in the next couple of days and then the version should be available.

Also, soon this will not be an issue anymore at all, because we will enable aiidalab to install app dependencies when needed.

**Pull request merged**
