### PR TITLE
Utilize ASE and pymatgen for structure format conversion

### LINKED ISSUE #30: New export formats
I suggest adding a few more export formats.
In particular, XSF? Maybe some more (you could check what ASE supports for instance)?

### LINKED ISSUE #44: Inaccessible providers/implementations not removed as intended
If a provider or a provider's implementation can not be reached or is not of the correct API version it should be removed from the dropdown list (at the moment after the fact).

This is currently not done properly and as intended in the code.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #30 

Add functionality to convert an OPTIMADE structure to another format _via_ ASE (`ase.Atoms.write()`) or pymatgen (`pymatgen.[Structure,Molecule].to()`).
Hence `ase` and `pymatgen` are also added to the list of install requirements.

Formats added in this PR:
- XYZ (ASE, pymatgen.Molecule)
- XSF (ASE, pymatgen.Structure)
- WIEN2k struct (ASE)
- VASP POSCAR (ASE)
- Quantum ESPRESSO in (ASE)

Formats extended in this PR:
- CIF (ASE, pymatgen.Structure)
- PDB (ASE, pymatgen.Molecule)

As is evident from the lists above, pymatgen is very selective to _only_ convert to certain formats depending on whether we have a pymatgen `Molecule` or `Structure`. This has currently been dealt with by emitting a warning (in the log) and disabling the "Download" button.

All of the conversion is done a bit more "safely" now as well, since it's all in a try/except block, where any `Exception` (or `Warning`) is caught, logged, and the "Download" button is disabled, `else` good-to-go.

[Test on binder (APP mode)](https://mybinder.org/v2/gh/CasperWA/aiidalab-optimade/close_30_new-export-formats?urlpath=%2Fapps%2FOPTIMADE_general.ipynb)
[Test on binder (Voilà)](https://mybinder.org/v2/gh/CasperWA/aiidalab-optimade/close_30_new-export-formats?urlpath=%2Fvoila%2Frender%2FOPTIMADE_general.ipynb)

### CODE REVIEW

**Comment by CasperWA** [comment]
There are still several things I am uncertain about:
- Should the void opportunities be removed from the dropdown list (e.g., when dealing with a `pymatgen.Structure` and `XYZ` is desired)?
- Should there be an extra dropdown list to separately determine the "proxy" package (i.e., ASE, pymatgen or local)
- Or should the mentioning of the "proxy" package be but _first_ in the names where applicable in the dropdown list, so it's easier to see all of those retrievable _via_ ASE bunched together?
- We could also completely remove redundancy and only use, e.g., ASE to create certain file types and then pymatgen for others, not mentioning explicitly which one is used?

**Comment by giovannipizzi** [comment]
Thanks, looks great! Also good that even if MC is down, once gets a nice error message and not a crash ;-) (at least in voila).

I like the way the list is sorted. For me the best is if you just remove from the list of formats those that are not valid. It's a bit weird if I select it but then the download button is disabled, it's not obvious why. For the rest, good to go! I think it's a good idea to mention the library (so someone else gets blamed in case of problems ;-) ), and I think it's ok if you pick only one library for a given format, depending on which one you feel it's more robust (e.g. XYZ is hard to crash, so just pick one). If the format is tricky, you might want to give more options.

**Comment by CasperWA** [comment]
> Thanks, looks great! Also good that even if MC is down, once gets a nice error message and not a crash ;-) (at least in voila).

Yeah. I think I'll start using Voilà exclusively for this, since I prefer its way of handling backend exceptions. If I get to log more extensively it should be enough as well to pick up on what went wrong, if the user didn't deliver good enough reproducibility feedback.

**Comment by CasperWA** [comment]
I have now removed `pymatgen`, and it seems clear why cif and pdb are there twice in the dropdown. It could still be optimized further (e.g., checking if `ase` is installed and use it exclusively for also cif and pdb). Or further intelligence by checking all of the 3rd party packages installed and add a dropdown for which to choose (or add the options dynamically to a single dropdown) and dynamically update the list according to the structure chosen and what formats are supported for it (this seems only to be an issue for `pymatgen`'s `Structure` vs. `Molecule`).

**Pull request merged**
